version: 2
builds:
  - binary: chrome-protocol-proxy
    ldflags: -s -extldflags "-static" -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64

archives:
  - formats: ["tar.gz"]
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md

homebrew_casks:
  - name: chrome-protocol-proxy
    caveats: "Usage: chrome-protocol-proxy -i -m -r localhost:9222"
    homepage: "https://github.com/wendigo/chrome-protocol-proxy"
    description: "chrome-protocol-proxy is small reverse websocket proxy designed for chrome debugging protocol. It's purpose is to capture messages written to and received from Chrome Debugging Protocol, coalesce requests with responses, unpack messages from Target domain and provide easy to read, colored output."
    repository:
      owner: wendigo
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chrome-protocol-proxy"]
          end

dockers_v2:
  - images:
      - "wendigo/chrome-protocol-proxy"
    tags:
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - "latest"
    platforms:
      - linux/amd64
    dockerfile: Dockerfile
    labels:
      "org.label-schema.schema-version": "1.0"
      "org.label-schema.version": "{{.Version}}"
      "org.label-schema.name": "{{.ProjectName}}"
    extra_files:
      - docker/run.sh

scoops:
  - name: chrome-protocol-proxy
    repository:
      owner: wendigo
      name: scoop-bucket
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/wendigo/chrome-protocol-proxy"
    description: "chrome-protocol-proxy is small reverse websocket proxy designed for chrome debugging protocol. It's purpose is to capture messages written to and received from Chrome Debugging Protocol, coalesce requests with responses, unpack messages from Target domain and provide easy to read, colored output."
    license: MIT
