package main

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"sync"
	"time"

	"github.com/gorilla/websocket"
)

//go:embed ui.html
var uiHTML []byte

const (
	directionSend = "send" // client -> browser
	directionRecv = "recv" // browser -> client

	// injectedIDBase is where ids of commands sent from the UI start. The range is
	// far above ids generated by typical clients (which count up from 1), so responses
	// to injected commands can be told apart and kept away from the proxied client.
	injectedIDBase = uint64(1_000_000_000)

	recentFramesLimit  = 500
	uiClientBufferSize = recentFramesLimit + 512
)

type uiFrame struct {
	Type string `json:"type"`
	// Boot identifies the proxy process and Seq numbers frames within it, so a
	// reconnecting UI can skip frames it already has when the recent buffer is
	// replayed to it.
	Boot      string          `json:"boot"`
	Seq       uint64          `json:"seq"`
	ConnID    string          `json:"connId"`
	Direction string          `json:"direction"`
	Timestamp int64           `json:"ts"`
	Injected  bool            `json:"injected"`
	Message   json.RawMessage `json:"message"`
}

type uiConnInfo struct {
	ID       string `json:"id"`
	Endpoint string `json:"endpoint"`
}

type uiConnectionsMessage struct {
	Type        string       `json:"type"`
	Connections []uiConnInfo `json:"connections"`
}

type uiErrorMessage struct {
	Type    string `json:"type"`
	Message string `json:"message"`
}

type uiCommand struct {
	Type      string          `json:"type"`
	ConnID    string          `json:"connId"`
	Method    string          `json:"method"`
	SessionID string          `json:"sessionId"`
	Params    json.RawMessage `json:"params"`
}

// proxiedConnection tracks a single client<->browser websocket pair so the UI can
// list it and inject commands into the browser-bound side.
type proxiedConnection struct {
	id       string
	endpoint string

	browser *websocket.Conn
	writeMu sync.Mutex

	injectedMu sync.Mutex
	injected   map[uint64]bool
}

// writeToBrowser serializes writes to the browser socket between the proxy
// goroutine and UI command injection.
func (c *proxiedConnection) writeToBrowser(messageType int, data []byte) error {
	c.writeMu.Lock()
	defer c.writeMu.Unlock()

	return c.browser.WriteMessage(messageType, data)
}

func (c *proxiedConnection) markInjected(id uint64) {
	c.injectedMu.Lock()
	defer c.injectedMu.Unlock()

	c.injected[id] = true
}

// claimInjectedResponse reports whether msg is the response to a command injected
// from the UI and, if so, consumes the pending id.
func (c *proxiedConnection) claimInjectedResponse(msg *protocolMessage) bool {
	if msg == nil || msg.ID == 0 || msg.Method != "" {
		return false
	}

	c.injectedMu.Lock()
	defer c.injectedMu.Unlock()

	if c.injected[msg.ID] {
		delete(c.injected, msg.ID)
		return true
	}

	return false
}

type uiHub struct {
	mu             sync.Mutex
	clients        map[*websocket.Conn]chan []byte
	conns          map[string]*proxiedConnection
	recent         [][]byte
	bootID         string
	frameSeq       uint64
	connSeq        uint64
	nextInjectedID uint64
}

var hub = &uiHub{
	clients:        make(map[*websocket.Conn]chan []byte),
	conns:          make(map[string]*proxiedConnection),
	bootID:         fmt.Sprintf("%d-%d", os.Getpid(), time.Now().UnixNano()),
	nextInjectedID: injectedIDBase,
}

func (h *uiHub) register(inspectorID, endpoint string, browser *websocket.Conn) *proxiedConnection {
	h.mu.Lock()

	h.connSeq++
	conn := &proxiedConnection{
		id:       fmt.Sprintf("%s#%d", inspectorID, h.connSeq),
		endpoint: endpoint,
		browser:  browser,
		injected: make(map[uint64]bool),
	}
	h.conns[conn.id] = conn

	h.broadcastConnectionsLocked()
	h.mu.Unlock()

	return conn
}

func (h *uiHub) unregister(conn *proxiedConnection) {
	h.mu.Lock()
	delete(h.conns, conn.id)
	h.broadcastConnectionsLocked()
	h.mu.Unlock()
}

func (h *uiHub) connectionsMessageLocked() []byte {
	msg := uiConnectionsMessage{Type: "connections", Connections: []uiConnInfo{}}

	for _, conn := range h.conns {
		msg.Connections = append(msg.Connections, uiConnInfo{ID: conn.id, Endpoint: conn.endpoint})
	}

	buf, err := json.Marshal(msg)
	if err != nil {
		return nil
	}

	return buf
}

func (h *uiHub) broadcastConnectionsLocked() {
	if buf := h.connectionsMessageLocked(); buf != nil {
		for _, ch := range h.clients {
			select {
			case ch <- buf:
			default:
			}
		}
	}
}

// publishFrame pushes a captured protocol frame to all connected UI clients. Frames
// that are not valid JSON are skipped, mirroring what the terminal logger accepts.
func (h *uiHub) publishFrame(conn *proxiedConnection, direction string, raw []byte, injected bool) {
	if !*flagUI || !json.Valid(raw) {
		return
	}

	h.mu.Lock()

	h.frameSeq++

	frame := uiFrame{
		Type:      "frame",
		Boot:      h.bootID,
		Seq:       h.frameSeq,
		ConnID:    conn.id,
		Direction: direction,
		Timestamp: time.Now().UnixMilli(),
		Injected:  injected,
		Message:   json.RawMessage(raw),
	}

	buf, err := json.Marshal(frame)
	if err != nil {
		h.mu.Unlock()
		return
	}

	h.recent = append(h.recent, buf)
	if len(h.recent) > recentFramesLimit {
		h.recent = h.recent[len(h.recent)-recentFramesLimit:]
	}

	for _, ch := range h.clients {
		select {
		case ch <- buf:
		default:
		}
	}
	h.mu.Unlock()
}

// inject sends a command from the UI into the browser-bound side of a proxied
// connection. The response is intercepted in proxyWS and only shown in the UI.
func (h *uiHub) inject(cmd *uiCommand) error {
	if cmd.Method == "" {
		return fmt.Errorf("method is required")
	}

	if len(cmd.Params) > 0 && !json.Valid(cmd.Params) {
		return fmt.Errorf("params is not valid JSON")
	}

	h.mu.Lock()
	conn := h.conns[cmd.ConnID]
	h.nextInjectedID++
	id := h.nextInjectedID
	h.mu.Unlock()

	if conn == nil {
		return fmt.Errorf("unknown connection: %q", cmd.ConnID)
	}

	msg := map[string]interface{}{
		"id":     id,
		"method": cmd.Method,
	}

	if len(cmd.Params) > 0 {
		msg["params"] = json.RawMessage(cmd.Params)
	}

	if cmd.SessionID != "" {
		msg["sessionId"] = cmd.SessionID
	}

	buf, err := json.Marshal(msg)
	if err != nil {
		return err
	}

	conn.markInjected(id)

	if err := conn.writeToBrowser(websocket.TextMessage, buf); err != nil {
		return fmt.Errorf("could not send command: %v", err)
	}

	h.publishFrame(conn, directionSend, buf, true)

	return nil
}

func (h *uiHub) addClient(c *websocket.Conn) chan []byte {
	ch := make(chan []byte, uiClientBufferSize)

	h.mu.Lock()
	h.clients[c] = ch

	if buf := h.connectionsMessageLocked(); buf != nil {
		ch <- buf
	}

	for _, buf := range h.recent {
		select {
		case ch <- buf:
		default:
		}
	}
	h.mu.Unlock()

	return ch
}

func (h *uiHub) removeClient(c *websocket.Conn) {
	h.mu.Lock()
	if ch, exists := h.clients[c]; exists {
		delete(h.clients, c)
		close(ch)
	}
	h.mu.Unlock()
}

func (h *uiHub) sendError(c *websocket.Conn, message string) {
	buf, err := json.Marshal(uiErrorMessage{Type: "error", Message: message})
	if err != nil {
		return
	}

	h.mu.Lock()
	if ch, exists := h.clients[c]; exists {
		select {
		case ch <- buf:
		default:
		}
	}
	h.mu.Unlock()
}

func serveUI(res http.ResponseWriter, req *http.Request) {
	res.Header().Set("Content-Type", "text/html; charset=utf-8")
	res.Write(uiHTML)
}

func uiWSHandler(res http.ResponseWriter, req *http.Request) {
	c, err := wsUpgrader.Upgrade(res, req, nil)
	if err != nil {
		return
	}

	ch := hub.addClient(c)

	go func() {
		for buf := range ch {
			if c.WriteMessage(websocket.TextMessage, buf) != nil {
				break
			}
		}

		c.Close()
	}()

	defer hub.removeClient(c)

	for {
		_, buf, err := c.ReadMessage()
		if err != nil {
			return
		}

		var cmd uiCommand
		if err := json.Unmarshal(buf, &cmd); err != nil {
			hub.sendError(c, fmt.Sprintf("could not parse command: %v", err))
			continue
		}

		if cmd.Type == "send" {
			if err := hub.inject(&cmd); err != nil {
				hub.sendError(c, err.Error())
			}
		}
	}
}
