on:
  push:
    branches:
      - master
  pull_request:
name: CI
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: build
        run: go build ./...
      - name: vet
        run: go vet ./...
      - name: test
        run: go test ./...
